//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Input/PlayerActionControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerActionControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerActionControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerActionControls"",
    ""maps"": [
        {
            ""name"": ""PC1Player"",
            ""id"": ""9a165b96-0998-42e4-b56d-2fc0cc6c06c8"",
            ""actions"": [
                {
                    ""name"": ""PC1PlayerMovement"",
                    ""type"": ""Value"",
                    ""id"": ""1da9de5d-dfb4-456a-86dd-da558ad4a4ad"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PC1PlayerExit"",
                    ""type"": ""Button"",
                    ""id"": ""a7afc59e-bef8-4858-8cc8-c6704164bd3d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PC1PlayerInteract"",
                    ""type"": ""Button"",
                    ""id"": ""906d96bb-8f8d-4ba4-a842-83e11f4629b9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""0fb5c01b-f3f8-4368-a2cb-8b06a3d37206"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC1PlayerMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""84eb54cf-c499-4426-a32a-b7253255d6cb"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC1PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b5a8cd68-5ccf-4bb6-9556-c2d79210fdc1"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC1PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""bf8a85de-2ec8-4555-ac2b-f6f3dcbdb183"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC1PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""1cba6fc1-a382-4f27-9617-e981fe20b8d5"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC1PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""04b57abd-5e0a-46cd-be2c-bcbd1d049bdb"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC1PlayerExit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0bacf99c-6850-4e7f-81fa-b5d04012da18"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC1PlayerInteract"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PC2Player"",
            ""id"": ""8b6a6443-2dd3-438e-9ad2-106ba53809ce"",
            ""actions"": [
                {
                    ""name"": ""PC2PlayerMovement"",
                    ""type"": ""Value"",
                    ""id"": ""c3d26c4f-a017-4548-a60b-9104fcb62af9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PC2PlayerExit"",
                    ""type"": ""Button"",
                    ""id"": ""835e28a5-9a5b-439c-b973-68a7f09b1ade"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PC2PlayerInteract"",
                    ""type"": ""Button"",
                    ""id"": ""8d87e8dd-11c5-43b7-8459-e3a4a7ab78bf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""e8d78827-5ea2-4ae2-97c3-ebfbd9a182fd"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC2PlayerMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d1f422b7-9d14-469c-85f8-8a1edf363fea"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC2PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e6d17a8d-d65e-4405-a1d2-945056cf9392"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC2PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a3b9558e-104f-4a8a-a802-1fdc5cea8fd2"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC2PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""5b5fdd56-900d-4425-9371-5c3035f2f698"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC2PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""6f60dea4-1aa2-4748-9010-c17cf1981fef"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC2PlayerExit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""83f00f47-6abb-40d1-9183-d07ef7145d9a"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC2PlayerInteract"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PC3Player"",
            ""id"": ""bf20d011-43cc-43dd-a708-effec82dede0"",
            ""actions"": [
                {
                    ""name"": ""PC3PlayerMovement"",
                    ""type"": ""Value"",
                    ""id"": ""a22653cd-154b-4fc1-8c55-6656cc6de1ea"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PC3PlayerExit"",
                    ""type"": ""Button"",
                    ""id"": ""1a138063-39aa-47f9-ab1c-fc654c09a6b2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PC3PlayerInteract"",
                    ""type"": ""Button"",
                    ""id"": ""a75d4879-cc30-4add-8567-42a5f3bbbd17"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""c0f5ed91-f395-4052-93be-805a35570d2e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC3PlayerMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""58728744-9159-4dcf-a91e-1c30871a5c73"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC3PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""27b1cb66-c6f4-446a-8859-fefc9be7589b"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC3PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c7514b56-a7be-42a8-969a-c4d014c5062b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC3PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""161a7983-9b3d-4caa-a37e-73def744c529"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC3PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""174846c2-1f5c-40e6-aec1-3610aaaaae58"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC3PlayerExit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b43f82d8-31b8-491b-b6ab-3a65adbf7367"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC3PlayerInteract"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PC4Player"",
            ""id"": ""20ffd174-85fc-496e-ae76-2d033731c7cd"",
            ""actions"": [
                {
                    ""name"": ""PC4PlayerMovement"",
                    ""type"": ""Value"",
                    ""id"": ""1c5ff82f-16ac-46e8-a4d8-5b667f242395"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PC4PlayerExit"",
                    ""type"": ""Button"",
                    ""id"": ""c92211a9-f687-42da-8680-8d21278a4436"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PC4PlayerInteract"",
                    ""type"": ""Button"",
                    ""id"": ""27ecd700-b74c-4a76-bd25-d45a0db62e73"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""1842ab7c-caa1-4ff9-91db-baf4a40dcd7f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC4PlayerMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c3253679-8413-4a46-aaf6-61f5124f8275"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC4PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0ecf0700-88e9-47f3-bd49-922378a32f1f"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC4PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""dd309c1e-8560-449e-9426-abca4eae1174"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC4PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""048c2a85-8edf-48d1-8b1e-cdc8eaa6aff1"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC4PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""2981d04b-7499-44b8-9847-d865089476be"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC4PlayerExit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3999b9c5-08c0-4658-bcbc-252dc84c4a5b"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC4PlayerInteract"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PC5Player"",
            ""id"": ""e14bc196-dd45-4412-ab28-0e391c364072"",
            ""actions"": [
                {
                    ""name"": ""PC5PlayerMovement"",
                    ""type"": ""Value"",
                    ""id"": ""cb286934-0a7d-41bc-aa14-ef1f769df8ad"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PC5PlayerExit"",
                    ""type"": ""Button"",
                    ""id"": ""9e1f3dbd-6114-484c-b966-d46ad0e5a339"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PC5PlayerInteract"",
                    ""type"": ""Button"",
                    ""id"": ""92a96456-1ffa-4979-bdd5-0d881aeb8e4e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""739bcbf6-f5a0-49f3-abb3-401856c2de95"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC5PlayerMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""24feedb1-f24d-47fd-92d6-c132bd23c076"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC5PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""13b44fea-51fa-4a40-a94a-5653b388e284"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC5PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b325eaf9-1f19-49a3-abb8-a82f27ace5c9"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC5PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""41e3264e-cda5-4600-9c27-2032ceb4bda6"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC5PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f9ff5f54-e95f-4e09-97f8-8ffa62a82b59"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC5PlayerExit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a77fc985-e94c-4381-9ee7-19ba40638b29"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PC5PlayerInteract"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Player"",
            ""id"": ""ed4df371-69c5-438d-b07b-ddc53d2c0492"",
            ""actions"": [
                {
                    ""name"": ""PlayerMovement"",
                    ""type"": ""Value"",
                    ""id"": ""586d747c-8863-4d73-8106-938f146b52e3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PlayerLook"",
                    ""type"": ""Value"",
                    ""id"": ""d390596d-9b07-48fe-8a5b-f154034600a1"",
                    ""expectedControlType"": ""Delta"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PlayerSprint"",
                    ""type"": ""Button"",
                    ""id"": ""029feebe-81a3-4f46-92d1-6593cefc6a78"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlayerInteract"",
                    ""type"": ""Button"",
                    ""id"": ""0b4f43c1-7b88-4598-9973-fa7d545590e6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""f757ccd3-b788-420a-8913-96f95ee457bd"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""1b36fdce-8210-4829-819c-c6b8b94f9251"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""8b65a926-b10e-43a7-b6bf-e43989cfcec8"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""6bb5813f-96a0-4251-81dd-d992f0e62956"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""dce4935c-061d-4675-808e-8c138fad7516"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1ffdbb4f-e844-44d8-a040-d9c7e6580c5d"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b247ee9b-4bf4-4b35-a7b4-796be364a8c1"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerSprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""794ffe29-6acb-44ed-80b5-89c185bcff25"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerInteract"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PC1Player
        m_PC1Player = asset.FindActionMap("PC1Player", throwIfNotFound: true);
        m_PC1Player_PC1PlayerMovement = m_PC1Player.FindAction("PC1PlayerMovement", throwIfNotFound: true);
        m_PC1Player_PC1PlayerExit = m_PC1Player.FindAction("PC1PlayerExit", throwIfNotFound: true);
        m_PC1Player_PC1PlayerInteract = m_PC1Player.FindAction("PC1PlayerInteract", throwIfNotFound: true);
        // PC2Player
        m_PC2Player = asset.FindActionMap("PC2Player", throwIfNotFound: true);
        m_PC2Player_PC2PlayerMovement = m_PC2Player.FindAction("PC2PlayerMovement", throwIfNotFound: true);
        m_PC2Player_PC2PlayerExit = m_PC2Player.FindAction("PC2PlayerExit", throwIfNotFound: true);
        m_PC2Player_PC2PlayerInteract = m_PC2Player.FindAction("PC2PlayerInteract", throwIfNotFound: true);
        // PC3Player
        m_PC3Player = asset.FindActionMap("PC3Player", throwIfNotFound: true);
        m_PC3Player_PC3PlayerMovement = m_PC3Player.FindAction("PC3PlayerMovement", throwIfNotFound: true);
        m_PC3Player_PC3PlayerExit = m_PC3Player.FindAction("PC3PlayerExit", throwIfNotFound: true);
        m_PC3Player_PC3PlayerInteract = m_PC3Player.FindAction("PC3PlayerInteract", throwIfNotFound: true);
        // PC4Player
        m_PC4Player = asset.FindActionMap("PC4Player", throwIfNotFound: true);
        m_PC4Player_PC4PlayerMovement = m_PC4Player.FindAction("PC4PlayerMovement", throwIfNotFound: true);
        m_PC4Player_PC4PlayerExit = m_PC4Player.FindAction("PC4PlayerExit", throwIfNotFound: true);
        m_PC4Player_PC4PlayerInteract = m_PC4Player.FindAction("PC4PlayerInteract", throwIfNotFound: true);
        // PC5Player
        m_PC5Player = asset.FindActionMap("PC5Player", throwIfNotFound: true);
        m_PC5Player_PC5PlayerMovement = m_PC5Player.FindAction("PC5PlayerMovement", throwIfNotFound: true);
        m_PC5Player_PC5PlayerExit = m_PC5Player.FindAction("PC5PlayerExit", throwIfNotFound: true);
        m_PC5Player_PC5PlayerInteract = m_PC5Player.FindAction("PC5PlayerInteract", throwIfNotFound: true);
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_PlayerMovement = m_Player.FindAction("PlayerMovement", throwIfNotFound: true);
        m_Player_PlayerLook = m_Player.FindAction("PlayerLook", throwIfNotFound: true);
        m_Player_PlayerSprint = m_Player.FindAction("PlayerSprint", throwIfNotFound: true);
        m_Player_PlayerInteract = m_Player.FindAction("PlayerInteract", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PC1Player
    private readonly InputActionMap m_PC1Player;
    private IPC1PlayerActions m_PC1PlayerActionsCallbackInterface;
    private readonly InputAction m_PC1Player_PC1PlayerMovement;
    private readonly InputAction m_PC1Player_PC1PlayerExit;
    private readonly InputAction m_PC1Player_PC1PlayerInteract;
    public struct PC1PlayerActions
    {
        private @PlayerActionControls m_Wrapper;
        public PC1PlayerActions(@PlayerActionControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @PC1PlayerMovement => m_Wrapper.m_PC1Player_PC1PlayerMovement;
        public InputAction @PC1PlayerExit => m_Wrapper.m_PC1Player_PC1PlayerExit;
        public InputAction @PC1PlayerInteract => m_Wrapper.m_PC1Player_PC1PlayerInteract;
        public InputActionMap Get() { return m_Wrapper.m_PC1Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PC1PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPC1PlayerActions instance)
        {
            if (m_Wrapper.m_PC1PlayerActionsCallbackInterface != null)
            {
                @PC1PlayerMovement.started -= m_Wrapper.m_PC1PlayerActionsCallbackInterface.OnPC1PlayerMovement;
                @PC1PlayerMovement.performed -= m_Wrapper.m_PC1PlayerActionsCallbackInterface.OnPC1PlayerMovement;
                @PC1PlayerMovement.canceled -= m_Wrapper.m_PC1PlayerActionsCallbackInterface.OnPC1PlayerMovement;
                @PC1PlayerExit.started -= m_Wrapper.m_PC1PlayerActionsCallbackInterface.OnPC1PlayerExit;
                @PC1PlayerExit.performed -= m_Wrapper.m_PC1PlayerActionsCallbackInterface.OnPC1PlayerExit;
                @PC1PlayerExit.canceled -= m_Wrapper.m_PC1PlayerActionsCallbackInterface.OnPC1PlayerExit;
                @PC1PlayerInteract.started -= m_Wrapper.m_PC1PlayerActionsCallbackInterface.OnPC1PlayerInteract;
                @PC1PlayerInteract.performed -= m_Wrapper.m_PC1PlayerActionsCallbackInterface.OnPC1PlayerInteract;
                @PC1PlayerInteract.canceled -= m_Wrapper.m_PC1PlayerActionsCallbackInterface.OnPC1PlayerInteract;
            }
            m_Wrapper.m_PC1PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PC1PlayerMovement.started += instance.OnPC1PlayerMovement;
                @PC1PlayerMovement.performed += instance.OnPC1PlayerMovement;
                @PC1PlayerMovement.canceled += instance.OnPC1PlayerMovement;
                @PC1PlayerExit.started += instance.OnPC1PlayerExit;
                @PC1PlayerExit.performed += instance.OnPC1PlayerExit;
                @PC1PlayerExit.canceled += instance.OnPC1PlayerExit;
                @PC1PlayerInteract.started += instance.OnPC1PlayerInteract;
                @PC1PlayerInteract.performed += instance.OnPC1PlayerInteract;
                @PC1PlayerInteract.canceled += instance.OnPC1PlayerInteract;
            }
        }
    }
    public PC1PlayerActions @PC1Player => new PC1PlayerActions(this);

    // PC2Player
    private readonly InputActionMap m_PC2Player;
    private IPC2PlayerActions m_PC2PlayerActionsCallbackInterface;
    private readonly InputAction m_PC2Player_PC2PlayerMovement;
    private readonly InputAction m_PC2Player_PC2PlayerExit;
    private readonly InputAction m_PC2Player_PC2PlayerInteract;
    public struct PC2PlayerActions
    {
        private @PlayerActionControls m_Wrapper;
        public PC2PlayerActions(@PlayerActionControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @PC2PlayerMovement => m_Wrapper.m_PC2Player_PC2PlayerMovement;
        public InputAction @PC2PlayerExit => m_Wrapper.m_PC2Player_PC2PlayerExit;
        public InputAction @PC2PlayerInteract => m_Wrapper.m_PC2Player_PC2PlayerInteract;
        public InputActionMap Get() { return m_Wrapper.m_PC2Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PC2PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPC2PlayerActions instance)
        {
            if (m_Wrapper.m_PC2PlayerActionsCallbackInterface != null)
            {
                @PC2PlayerMovement.started -= m_Wrapper.m_PC2PlayerActionsCallbackInterface.OnPC2PlayerMovement;
                @PC2PlayerMovement.performed -= m_Wrapper.m_PC2PlayerActionsCallbackInterface.OnPC2PlayerMovement;
                @PC2PlayerMovement.canceled -= m_Wrapper.m_PC2PlayerActionsCallbackInterface.OnPC2PlayerMovement;
                @PC2PlayerExit.started -= m_Wrapper.m_PC2PlayerActionsCallbackInterface.OnPC2PlayerExit;
                @PC2PlayerExit.performed -= m_Wrapper.m_PC2PlayerActionsCallbackInterface.OnPC2PlayerExit;
                @PC2PlayerExit.canceled -= m_Wrapper.m_PC2PlayerActionsCallbackInterface.OnPC2PlayerExit;
                @PC2PlayerInteract.started -= m_Wrapper.m_PC2PlayerActionsCallbackInterface.OnPC2PlayerInteract;
                @PC2PlayerInteract.performed -= m_Wrapper.m_PC2PlayerActionsCallbackInterface.OnPC2PlayerInteract;
                @PC2PlayerInteract.canceled -= m_Wrapper.m_PC2PlayerActionsCallbackInterface.OnPC2PlayerInteract;
            }
            m_Wrapper.m_PC2PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PC2PlayerMovement.started += instance.OnPC2PlayerMovement;
                @PC2PlayerMovement.performed += instance.OnPC2PlayerMovement;
                @PC2PlayerMovement.canceled += instance.OnPC2PlayerMovement;
                @PC2PlayerExit.started += instance.OnPC2PlayerExit;
                @PC2PlayerExit.performed += instance.OnPC2PlayerExit;
                @PC2PlayerExit.canceled += instance.OnPC2PlayerExit;
                @PC2PlayerInteract.started += instance.OnPC2PlayerInteract;
                @PC2PlayerInteract.performed += instance.OnPC2PlayerInteract;
                @PC2PlayerInteract.canceled += instance.OnPC2PlayerInteract;
            }
        }
    }
    public PC2PlayerActions @PC2Player => new PC2PlayerActions(this);

    // PC3Player
    private readonly InputActionMap m_PC3Player;
    private IPC3PlayerActions m_PC3PlayerActionsCallbackInterface;
    private readonly InputAction m_PC3Player_PC3PlayerMovement;
    private readonly InputAction m_PC3Player_PC3PlayerExit;
    private readonly InputAction m_PC3Player_PC3PlayerInteract;
    public struct PC3PlayerActions
    {
        private @PlayerActionControls m_Wrapper;
        public PC3PlayerActions(@PlayerActionControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @PC3PlayerMovement => m_Wrapper.m_PC3Player_PC3PlayerMovement;
        public InputAction @PC3PlayerExit => m_Wrapper.m_PC3Player_PC3PlayerExit;
        public InputAction @PC3PlayerInteract => m_Wrapper.m_PC3Player_PC3PlayerInteract;
        public InputActionMap Get() { return m_Wrapper.m_PC3Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PC3PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPC3PlayerActions instance)
        {
            if (m_Wrapper.m_PC3PlayerActionsCallbackInterface != null)
            {
                @PC3PlayerMovement.started -= m_Wrapper.m_PC3PlayerActionsCallbackInterface.OnPC3PlayerMovement;
                @PC3PlayerMovement.performed -= m_Wrapper.m_PC3PlayerActionsCallbackInterface.OnPC3PlayerMovement;
                @PC3PlayerMovement.canceled -= m_Wrapper.m_PC3PlayerActionsCallbackInterface.OnPC3PlayerMovement;
                @PC3PlayerExit.started -= m_Wrapper.m_PC3PlayerActionsCallbackInterface.OnPC3PlayerExit;
                @PC3PlayerExit.performed -= m_Wrapper.m_PC3PlayerActionsCallbackInterface.OnPC3PlayerExit;
                @PC3PlayerExit.canceled -= m_Wrapper.m_PC3PlayerActionsCallbackInterface.OnPC3PlayerExit;
                @PC3PlayerInteract.started -= m_Wrapper.m_PC3PlayerActionsCallbackInterface.OnPC3PlayerInteract;
                @PC3PlayerInteract.performed -= m_Wrapper.m_PC3PlayerActionsCallbackInterface.OnPC3PlayerInteract;
                @PC3PlayerInteract.canceled -= m_Wrapper.m_PC3PlayerActionsCallbackInterface.OnPC3PlayerInteract;
            }
            m_Wrapper.m_PC3PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PC3PlayerMovement.started += instance.OnPC3PlayerMovement;
                @PC3PlayerMovement.performed += instance.OnPC3PlayerMovement;
                @PC3PlayerMovement.canceled += instance.OnPC3PlayerMovement;
                @PC3PlayerExit.started += instance.OnPC3PlayerExit;
                @PC3PlayerExit.performed += instance.OnPC3PlayerExit;
                @PC3PlayerExit.canceled += instance.OnPC3PlayerExit;
                @PC3PlayerInteract.started += instance.OnPC3PlayerInteract;
                @PC3PlayerInteract.performed += instance.OnPC3PlayerInteract;
                @PC3PlayerInteract.canceled += instance.OnPC3PlayerInteract;
            }
        }
    }
    public PC3PlayerActions @PC3Player => new PC3PlayerActions(this);

    // PC4Player
    private readonly InputActionMap m_PC4Player;
    private IPC4PlayerActions m_PC4PlayerActionsCallbackInterface;
    private readonly InputAction m_PC4Player_PC4PlayerMovement;
    private readonly InputAction m_PC4Player_PC4PlayerExit;
    private readonly InputAction m_PC4Player_PC4PlayerInteract;
    public struct PC4PlayerActions
    {
        private @PlayerActionControls m_Wrapper;
        public PC4PlayerActions(@PlayerActionControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @PC4PlayerMovement => m_Wrapper.m_PC4Player_PC4PlayerMovement;
        public InputAction @PC4PlayerExit => m_Wrapper.m_PC4Player_PC4PlayerExit;
        public InputAction @PC4PlayerInteract => m_Wrapper.m_PC4Player_PC4PlayerInteract;
        public InputActionMap Get() { return m_Wrapper.m_PC4Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PC4PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPC4PlayerActions instance)
        {
            if (m_Wrapper.m_PC4PlayerActionsCallbackInterface != null)
            {
                @PC4PlayerMovement.started -= m_Wrapper.m_PC4PlayerActionsCallbackInterface.OnPC4PlayerMovement;
                @PC4PlayerMovement.performed -= m_Wrapper.m_PC4PlayerActionsCallbackInterface.OnPC4PlayerMovement;
                @PC4PlayerMovement.canceled -= m_Wrapper.m_PC4PlayerActionsCallbackInterface.OnPC4PlayerMovement;
                @PC4PlayerExit.started -= m_Wrapper.m_PC4PlayerActionsCallbackInterface.OnPC4PlayerExit;
                @PC4PlayerExit.performed -= m_Wrapper.m_PC4PlayerActionsCallbackInterface.OnPC4PlayerExit;
                @PC4PlayerExit.canceled -= m_Wrapper.m_PC4PlayerActionsCallbackInterface.OnPC4PlayerExit;
                @PC4PlayerInteract.started -= m_Wrapper.m_PC4PlayerActionsCallbackInterface.OnPC4PlayerInteract;
                @PC4PlayerInteract.performed -= m_Wrapper.m_PC4PlayerActionsCallbackInterface.OnPC4PlayerInteract;
                @PC4PlayerInteract.canceled -= m_Wrapper.m_PC4PlayerActionsCallbackInterface.OnPC4PlayerInteract;
            }
            m_Wrapper.m_PC4PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PC4PlayerMovement.started += instance.OnPC4PlayerMovement;
                @PC4PlayerMovement.performed += instance.OnPC4PlayerMovement;
                @PC4PlayerMovement.canceled += instance.OnPC4PlayerMovement;
                @PC4PlayerExit.started += instance.OnPC4PlayerExit;
                @PC4PlayerExit.performed += instance.OnPC4PlayerExit;
                @PC4PlayerExit.canceled += instance.OnPC4PlayerExit;
                @PC4PlayerInteract.started += instance.OnPC4PlayerInteract;
                @PC4PlayerInteract.performed += instance.OnPC4PlayerInteract;
                @PC4PlayerInteract.canceled += instance.OnPC4PlayerInteract;
            }
        }
    }
    public PC4PlayerActions @PC4Player => new PC4PlayerActions(this);

    // PC5Player
    private readonly InputActionMap m_PC5Player;
    private IPC5PlayerActions m_PC5PlayerActionsCallbackInterface;
    private readonly InputAction m_PC5Player_PC5PlayerMovement;
    private readonly InputAction m_PC5Player_PC5PlayerExit;
    private readonly InputAction m_PC5Player_PC5PlayerInteract;
    public struct PC5PlayerActions
    {
        private @PlayerActionControls m_Wrapper;
        public PC5PlayerActions(@PlayerActionControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @PC5PlayerMovement => m_Wrapper.m_PC5Player_PC5PlayerMovement;
        public InputAction @PC5PlayerExit => m_Wrapper.m_PC5Player_PC5PlayerExit;
        public InputAction @PC5PlayerInteract => m_Wrapper.m_PC5Player_PC5PlayerInteract;
        public InputActionMap Get() { return m_Wrapper.m_PC5Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PC5PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPC5PlayerActions instance)
        {
            if (m_Wrapper.m_PC5PlayerActionsCallbackInterface != null)
            {
                @PC5PlayerMovement.started -= m_Wrapper.m_PC5PlayerActionsCallbackInterface.OnPC5PlayerMovement;
                @PC5PlayerMovement.performed -= m_Wrapper.m_PC5PlayerActionsCallbackInterface.OnPC5PlayerMovement;
                @PC5PlayerMovement.canceled -= m_Wrapper.m_PC5PlayerActionsCallbackInterface.OnPC5PlayerMovement;
                @PC5PlayerExit.started -= m_Wrapper.m_PC5PlayerActionsCallbackInterface.OnPC5PlayerExit;
                @PC5PlayerExit.performed -= m_Wrapper.m_PC5PlayerActionsCallbackInterface.OnPC5PlayerExit;
                @PC5PlayerExit.canceled -= m_Wrapper.m_PC5PlayerActionsCallbackInterface.OnPC5PlayerExit;
                @PC5PlayerInteract.started -= m_Wrapper.m_PC5PlayerActionsCallbackInterface.OnPC5PlayerInteract;
                @PC5PlayerInteract.performed -= m_Wrapper.m_PC5PlayerActionsCallbackInterface.OnPC5PlayerInteract;
                @PC5PlayerInteract.canceled -= m_Wrapper.m_PC5PlayerActionsCallbackInterface.OnPC5PlayerInteract;
            }
            m_Wrapper.m_PC5PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PC5PlayerMovement.started += instance.OnPC5PlayerMovement;
                @PC5PlayerMovement.performed += instance.OnPC5PlayerMovement;
                @PC5PlayerMovement.canceled += instance.OnPC5PlayerMovement;
                @PC5PlayerExit.started += instance.OnPC5PlayerExit;
                @PC5PlayerExit.performed += instance.OnPC5PlayerExit;
                @PC5PlayerExit.canceled += instance.OnPC5PlayerExit;
                @PC5PlayerInteract.started += instance.OnPC5PlayerInteract;
                @PC5PlayerInteract.performed += instance.OnPC5PlayerInteract;
                @PC5PlayerInteract.canceled += instance.OnPC5PlayerInteract;
            }
        }
    }
    public PC5PlayerActions @PC5Player => new PC5PlayerActions(this);

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_PlayerMovement;
    private readonly InputAction m_Player_PlayerLook;
    private readonly InputAction m_Player_PlayerSprint;
    private readonly InputAction m_Player_PlayerInteract;
    public struct PlayerActions
    {
        private @PlayerActionControls m_Wrapper;
        public PlayerActions(@PlayerActionControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @PlayerMovement => m_Wrapper.m_Player_PlayerMovement;
        public InputAction @PlayerLook => m_Wrapper.m_Player_PlayerLook;
        public InputAction @PlayerSprint => m_Wrapper.m_Player_PlayerSprint;
        public InputAction @PlayerInteract => m_Wrapper.m_Player_PlayerInteract;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @PlayerMovement.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPlayerMovement;
                @PlayerMovement.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPlayerMovement;
                @PlayerMovement.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPlayerMovement;
                @PlayerLook.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPlayerLook;
                @PlayerLook.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPlayerLook;
                @PlayerLook.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPlayerLook;
                @PlayerSprint.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPlayerSprint;
                @PlayerSprint.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPlayerSprint;
                @PlayerSprint.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPlayerSprint;
                @PlayerInteract.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPlayerInteract;
                @PlayerInteract.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPlayerInteract;
                @PlayerInteract.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPlayerInteract;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PlayerMovement.started += instance.OnPlayerMovement;
                @PlayerMovement.performed += instance.OnPlayerMovement;
                @PlayerMovement.canceled += instance.OnPlayerMovement;
                @PlayerLook.started += instance.OnPlayerLook;
                @PlayerLook.performed += instance.OnPlayerLook;
                @PlayerLook.canceled += instance.OnPlayerLook;
                @PlayerSprint.started += instance.OnPlayerSprint;
                @PlayerSprint.performed += instance.OnPlayerSprint;
                @PlayerSprint.canceled += instance.OnPlayerSprint;
                @PlayerInteract.started += instance.OnPlayerInteract;
                @PlayerInteract.performed += instance.OnPlayerInteract;
                @PlayerInteract.canceled += instance.OnPlayerInteract;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPC1PlayerActions
    {
        void OnPC1PlayerMovement(InputAction.CallbackContext context);
        void OnPC1PlayerExit(InputAction.CallbackContext context);
        void OnPC1PlayerInteract(InputAction.CallbackContext context);
    }
    public interface IPC2PlayerActions
    {
        void OnPC2PlayerMovement(InputAction.CallbackContext context);
        void OnPC2PlayerExit(InputAction.CallbackContext context);
        void OnPC2PlayerInteract(InputAction.CallbackContext context);
    }
    public interface IPC3PlayerActions
    {
        void OnPC3PlayerMovement(InputAction.CallbackContext context);
        void OnPC3PlayerExit(InputAction.CallbackContext context);
        void OnPC3PlayerInteract(InputAction.CallbackContext context);
    }
    public interface IPC4PlayerActions
    {
        void OnPC4PlayerMovement(InputAction.CallbackContext context);
        void OnPC4PlayerExit(InputAction.CallbackContext context);
        void OnPC4PlayerInteract(InputAction.CallbackContext context);
    }
    public interface IPC5PlayerActions
    {
        void OnPC5PlayerMovement(InputAction.CallbackContext context);
        void OnPC5PlayerExit(InputAction.CallbackContext context);
        void OnPC5PlayerInteract(InputAction.CallbackContext context);
    }
    public interface IPlayerActions
    {
        void OnPlayerMovement(InputAction.CallbackContext context);
        void OnPlayerLook(InputAction.CallbackContext context);
        void OnPlayerSprint(InputAction.CallbackContext context);
        void OnPlayerInteract(InputAction.CallbackContext context);
    }
}
